name: GeneratePdf

on:
  push:
    branches: [ testGeneration ]


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:

      - uses: actions/checkout@v2

      - name: LaTeX compilation
      # You may pin to the exact commit or the version.
      # uses: dante-ev/latex-action@259e5ff953ad4d4616fbd09cc87a526ee5c4499a
        uses: dante-ev/latex-action@v0.2.0
        with:
        # The root LaTeX file to be compiled
            root_file: Rulebook.tex 
    
      - name: Storing pdf 
        uses: actions/upload-artifact@v2
        with: 
          name: currentRulebook
          path: downloads
